### ISSUE TITLE
Bad Request - invalid_redirect

### ISSUE THREAD

**Issue by johnish** [cronofy/cronofy-php-sample-app#6]
I followed the instructions but I get

Bad Request
Code
invalid_redirect

Description
The redirect_uri was not provided or did not match the client's whitelist.

URL https://app.cronofy.com/oauth/authorize?response_type=code&client_id=CPnbEn14XRcDe-bMiHgk1xlW8gzxoToy&redirect_uri=local.cronofy.com%2Foauth%2F&scope=read_account%20create_calendar%20list_calendars%20read_events%20create_event%20delete_event%20read_free_busy%20change_participation_status

redirect_uri is what I typed in to the domain. Is it supposed to be a URL?

UPDATE: I changed domain to a URL and it seems to be working now. Perhaps instead of DOMAIN you can call this URL/URI?  

$GLOBALS['DOMAIN'] = "http://local.cronofy.com";

**Comment by ghost** [comment]
Hi I have the same problem but I do not understand how you fixed it.  Can you please elaborate?

**Comment by stephenbinns** [comment]
Hi Imogen, 

In the `globals.php` file you will need to set the setting for the `DOMAIN`

for example if you site is hosted locally you may use:
 `$GLOBALS['DOMAIN'] = "http://localhost/"`

Regards,
Stephen

**Comment by CronofyMatt** [comment]
Hi and thank you for taking the time to open this issue, and apologies for the delay in getting back. I hope that you were able to solve this issue as I understand it has been some time since it was first opened.

Due to the age of this issue I am going to close it for now, however if you are still having problems please either re-open the ticket, create a new issue, or contact us at [support@cronofy.com](mailto:support@cronofy.com) where our support and engineering teams can help you out.

We will be updating our monitoring of issues being opened on repos to make sure we don’t let issues stagnate in future. We put a lot of time and effort into the quality of our products and this falls below the standards of support and care we offer elsewhere.
